#!/usr/bin/env bash

if ! command -v cljfmt &> /dev/null
then
    echo "cljfmt could not be found. Please follow the installation instructions here https://github.com/weavejester/cljfmt"
    exit 2
fi

result=$(cljfmt fix $@ 2>&1)

if [ -z "$result" ]; then
    exit 0;
else
    echo $result
    exit 1;
fi
